### ISSUE TITLE
Account activity tab shows all account activity in School Idol Tomodachi instead.

### ISSUE THREAD

**Issue by MikuAuahDark** [SchoolIdolTomodachi/SchoolIdolAPI#174]
[This screenshot says everything](http://imgur.com/Z0KSmB3)

**Comment by db0company** [comment]
That's a temporary cached page that I return because the current code for the activities is very slow, which makes the site unusable after just a few minutes.

I think I know how to fix it, but I'll have to re-write a lot of code. I'll try to do it ASAP.

It's probably a bit confusing, so maybe I should just return a message that says it's temporarily disabled instead ^^'

**Comment by MikuAuahDark** [comment]
Okay, sorry for the long replay. Everything is working now (I assumed that you fix the activity thingy).
