### ISSUE TITLE
"Neither" Option in Contest

### ISSUE THREAD

**Issue by seacanaryy** [SchoolIdolTomodachi/SchoolIdolAPI#190]
sometimes ya get those cards that you really dont like and i dont wanna vote for either of them

**Comment by Engil** [comment]
Hi,
This has been removed from Contest some weeks ago (you were able to just hit F5 and vote again), now after skipping at least 5 votes you will be prompted with one of the skipped votes until you finally vote again.
The main idea was to avoid too much cheating, since some people were able to run bots that would just skip every vote until a specific idol or card showed up.
I hope you understand, I am still looking for a better solution that would enable voters to skip some votes, but that's the better solution I come up with for now.
Cheers,
