### ISSUE TITLE
Can't update teams.

### ISSUE THREAD

**Issue by normemes** [SchoolIdolTomodachi/SchoolIdolAPI#249]
I updated it a few months ago, and now I've been unable to update it.
![screen shot 2016-07-18 at 2 43 51 pm](https://cloud.githubusercontent.com/assets/20509901/16906179/155bf44c-4cf6-11e6-9b3a-d980f40f122d.png)

**Comment by db0company** [comment]
Unfortunately, I haven't been able to identify the reason why it does that. For now, to fix your team, please delete it and re-create it.

**Comment by ShadeRunner7** [comment]
Is this fixed? Works for me at least.

**Comment by KTwilt** [comment]
I think the error happens when you are rearranging members that are already in your team.  I'm not getting an error if I replace a card with one that is not in the team.  If, for example, I want to keep the team the same but switch which girl is the center, it results in an error.  

Oddly enough, hitting the back button at the error screen, the team looks like how it should if the switch worked.  But a refresh, or navigating back to the Teams page, shows that the change doesn't stick.
